import Head from 'next/head'
import styles from '../styles/Home.module.css'
import sidebarStyles from '../styles/Sidebar.module.css'
import Auth from '../components/Auth'
import Chat from '../components/Chat'
import DirectMessages from '../components/DirectMessages'
import Profile from '../components/Profile'

import { useEffect, useRef, useState } from 'react'

export default function Home({ currentUser, session, supabase }) {
  const [loggedIn, setLoggedIn] = useState(false)
  const [tab, setTab] = useState('public') // 'public' | 'private' | 'profile'
  const [sidebarOpen, setSidebarOpen] = useState(true) // Default open on desktop
  const [isDesktop, setIsDesktop] = useState(true)

  const directMessagesRef = useRef(null)

  useEffect(()=> {
    setLoggedIn(!! session)
    
    // Check if desktop
    const checkDesktop = () => {
      setIsDesktop(window.innerWidth > 768)
    }
    checkDesktop()
    window.addEventListener('resize', checkDesktop)
    return () => window.removeEventListener('resize', checkDesktop)
  }, [session])

  const handleOpenDirectMessages = (userId) => {
    setTab('private')
    setTimeout(() => {
      directMessagesRef.current?.openThreadWith(userId)
    }, 0)
  }

  const getAvatarLetter = () => {
    const name = currentUser?.username || session?.user?.email || 'U'
    return name[0].toUpperCase()
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Supabase Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>

      <main className={styles.main} style={{ 
        marginRight: loggedIn && isDesktop && sidebarOpen ? '280px' : '0', 
        transition: 'margin-right 0.3s ease' 
      }}>
        {loggedIn? (
          tab === 'profile' ? (
            <Profile currentUser={currentUser} session={session} supabase={supabase} onBack={() => setTab('public')} />
          ) : tab === 'public' ? (
            <Chat currentUser = { currentUser } session = {session} supabase = { supabase } onOpenDirectMessages={handleOpenDirectMessages} />
          ) : (
            <DirectMessages
              ref={directMessagesRef}
              currentUser = { currentUser }
              session = {session}
              supabase = { supabase }
            />
          )
        ) : (
          <Auth supabase = { supabase } />
        )}
      </main>

      {/* Sidebar Navigation */}
      {loggedIn && (
        <>
          <div className={`${sidebarStyles.sidebarOverlay} ${sidebarOpen ? sidebarStyles.open : ''}`} 
               onClick={() => setSidebarOpen(false)} />
          
          <div className={`${sidebarStyles.sidebar} ${sidebarOpen ? sidebarStyles.open : ''} ${!sidebarOpen && isDesktop ? sidebarStyles.closed : ''}`}>
            <div className={sidebarStyles.sidebarHeader}>
              <h2>القائمة</h2>
              <p>اختر الصفحة المطلوبة</p>
            </div>

            <div className={sidebarStyles.navItems}>
              <div 
                className={`${sidebarStyles.navItem} ${tab === 'public' ? sidebarStyles.active : ''}`}
                onClick={() => {
                  setTab('public')
                  setSidebarOpen(false)
                }}
              >
                <div className={sidebarStyles.navItemIcon}>💬</div>
                <div className={sidebarStyles.navItemText}>المحادثة العامة</div>
              </div>

              <div 
                className={`${sidebarStyles.navItem} ${tab === 'private' ? sidebarStyles.active : ''}`}
                onClick={() => {
                  setTab('private')
                  setSidebarOpen(false)
                }}
              >
                <div className={sidebarStyles.navItemIcon}>🔒</div>
                <div className={sidebarStyles.navItemText}>المحادثات الخاصة</div>
              </div>

              <div 
                className={`${sidebarStyles.navItem} ${tab === 'profile' ? sidebarStyles.active : ''}`}
                onClick={() => {
                  setTab('profile')
                  setSidebarOpen(false)
                }}
              >
                <div className={sidebarStyles.navItemIcon}>👤</div>
                <div className={sidebarStyles.navItemText}>الملف الشخصي</div>
              </div>
            </div>

            <div className={sidebarStyles.userInfo}>
              <div className={sidebarStyles.userAvatar}>
                {getAvatarLetter()}
              </div>
              <div className={sidebarStyles.userName}>
                {currentUser?.username || 'بدون اسم'}
              </div>
              <div className={sidebarStyles.userEmail}>
                {session?.user?.email}
              </div>
            </div>
          </div>

          {/* Mobile Toggle Button */}
          <button 
            className={sidebarStyles.sidebarToggle}
            onClick={() => setSidebarOpen(!sidebarOpen)}
          >
            {sidebarOpen ? '✕' : '☰'}
          </button>
        </>
      )}
    </div>
  )
}
